name: github pages

on:
  push:
    branches:
      - main  # Set a branch to deploy
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0  # Change if you need git info

      - name: Setup Zig
        uses: goto-bus-stop/setup-zig@v2
        working-directory: ./docs 
        with:
          version: 0.12.0-dev.3381+7057bffc1
          cache: true
          
      - name: Restore cache
        uses: actions/cache/restore@v3
        working-directory: ./docs
        with:
          path: |
            ~/.cache/zig
            zig-cache
          key: zine-${{hashFiles('build.zig.zon')}}          

      - name: Build
        working-directory: ./docs
        run: zig build --summary all
          
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        working-directory: ./docs
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./zig-out
          
      - name: Save Cache
        uses: actions/cache/save@v3
        working-directory: ./docs
        with:
          path: |
            ~/.cache/zig
            zig-cache
          key: zine-${{hashFiles('build.zig.zon')}}   
